// Suggested hops in CategorySelect and Autocomplete
const hopSuggestions = [
  { name: "Astra", id: "astra" },
  { name: "Eclipse", id: "eclipse" },
  { name: "Ella", id: "ella" },
  { name: "Enigma", id: "enigma" },
  { name: "Feux-Coeur Francais", id: "feux-coeur-francais" },
  { name: "Galaxy", id: "galaxy" },
  { name: "Helga", id: "helga" },
  { name: "HPA-016", id: "hpa-016" },
  { name: "Melba", id: "melba" },
  { name: "Pride of Ringwood", id: "pride-of-ringwood" },
  { name: "Summer", id: "summer" },
  { name: "Super Pride", id: "super-pride" },
  { name: "Sylva", id: "sylva" },
  { name: "Topaz", id: "topaz" },
  { name: "Vic Secret", id: "vic-secret" },
  { name: "Vienna Gold", id: "vienna-gold" },
  { name: "Canadian Redvine", id: "canadian-redvine" },
  { name: "Lumberjack", id: "lumberjack" },
  { name: "Sasquatch", id: "sasquatch" },
  { name: "Wild Loyalist", id: "wild-loyalist" },
  { name: "Marco Polo", id: "marco-polo" },
  { name: "Tsingdao Flower", id: "tsingdao-flower" },
  { name: "Agnus", id: "agnus" },
  { name: "Amethyst", id: "amethyst" },
  { name: "Bohemie", id: "bohemie" },
  { name: "Boomerang", id: "boomerang" },
  { name: "Bor", id: "bor" },
  { name: "Gaia", id: "gaia" },
  { name: "Harmonie", id: "harmonie" },
  { name: "Kazbek", id: "kazbek" },
  { name: "Mimosa", id: "mimosa" },
  { name: "Premiant", id: "premiant" },
  { name: "Saaz (CZ)", id: "saaz-cz" },
  { name: "Saaz Late", id: "saaz-late" },
  { name: "Sládek", id: "sládek" },
  { name: "Vital", id: "vital" },
  { name: "Aramis", id: "aramis" },
  { name: "Barbe Rouge", id: "barbe-rouge" },
  { name: "Bouclier", id: "bouclier" },
  { name: "Elixir", id: "elixir" },
  { name: "Mistral", id: "mistral" },
  { name: "Petit Blanc", id: "petit-blanc" },
  { name: "Strisselspalt", id: "strisselspalt" },
  { name: "Tardif de Bourgogne", id: "tardif-de-bourgogne" },
  { name: "Triskel", id: "triskel" },
  { name: "Akoya", id: "akoya" },
  { name: "Ariana", id: "ariana" },
  { name: "Aurum", id: "aurum" },
  { name: "Brewer's Gold (GR)", id: "brewer's-gold" },
  { name: "Callista", id: "callista" },
  { name: "Diamant", id: "diamant" },
  { name: "Hallertau Blanc", id: "hallertau-blanc" },
  { name: "Hallertau Gold", id: "hallertau-gold" },
  { name: "Hallertau Mittelfrüh", id: "hallertau-mittelfrüh" },
  { name: "Hallertau Tradition", id: "hallertau-tradition" },
  { name: "Herkules", id: "herkules" },
  { name: "Hersbrucker", id: "hersbrucker" },
  { name: "Huell Melon", id: "huell-melon" },
  { name: "Hüller Bitterer", id: "hüller-bitterer" },
  { name: "Magnum (GR)", id: "magnum" },
  { name: "Mandarina Bavaria", id: "mandarina-bavaria" },
  { name: "Merkur", id: "merkur" },
  { name: "Monroe", id: "monroe" },
  { name: "Northern Brewer (GR)", id: "northern-brewer" },
  { name: "Opal", id: "opal" },
  { name: "Orion", id: "orion" },
  { name: "Perle (GR)", id: "perle" },
  { name: "Polaris", id: "polaris" },
  { name: "Relax", id: "relax" },
  { name: "Saphir", id: "saphir" },
  { name: "Smaragd", id: "smaragd" },
  { name: "Solero", id: "solero" },
  { name: "Spalt", id: "spalt" },
  { name: "Spalter Select", id: "spalter-select" },
  { name: "Tango", id: "tango" },
  { name: "Tettnanger", id: "tettnanger" },
  { name: "Wurttemberg", id: "wurttemberg" },
  { name: "Yellow Sub", id: "yellow-sub" },
  { name: "Golden Star", id: "golden-star" },
  { name: "Sorachi Ace", id: "sorachi-ace" },
  { name: "Toyomidori", id: "toyomidori" },
  { name: "Brooklyn", id: "brooklyn" },
  { name: "Dr. Rudi", id: "dr-rudi" },
  { name: "Green Bullet", id: "green-bullet" },
  { name: "HORT9909", id: "hort9909" },
  { name: "Kohatu", id: "kohatu" },
  { name: "Motueka", id: "motueka" },
  { name: "Moutere", id: "moutere" },
  { name: "Nectaron", id: "nectaron" },
  { name: "Nelson Sauvin", id: "nelson-sauvin" },
  { name: "NZH-107", id: "nzh-107" },
  { name: "Pacific Gem", id: "pacific-gem" },
  { name: "Pacific Jade", id: "pacific-jade" },
  { name: "Pacific Sunrise", id: "pacific-sunrise" },
  { name: "Pacifica", id: "pacifica" },
  { name: "Rakau", id: "rakau" },
  { name: "Riwaka", id: "riwaka" },
  { name: "Smooth Cone", id: "smooth-cone" },
  { name: "Southern Cross", id: "southern-cross" },
  { name: "Sticklebract", id: "sticklebract" },
  { name: "Taiheke", id: "taiheke" },
  { name: "Wai-iti", id: "wai-iti" },
  { name: "Waimea", id: "waimea" },
  { name: "Wakatu", id: "wakatu" },
  { name: "Junga", id: "junga" },
  { name: "Limbus", id: "limbus" },
  { name: "Lubelska", id: "lubelska" },
  { name: "Magnat", id: "magnat" },
  { name: "Marynka", id: "marynka" },
  { name: "Pulawski", id: "pulawski" },
  { name: "Sybilla", id: "sybilla" },
  { name: "Zula", id: "zula" },
  { name: "Apolon", id: "apolon" },
  { name: "Atlas", id: "atlas" },
  { name: "Aurora", id: "aurora" },
  { name: "Bobek", id: "bobek" },
  { name: "Cekin", id: "cekin" },
  { name: "Celeia", id: "celeia" },
  { name: "Dana", id: "dana" },
  { name: "Styrian Cardinal", id: "styrian-cardinal" },
  { name: "Styrian Dragon", id: "styrian-dragon" },
  { name: "Styrian Eagle", id: "styrian-eagle" },
  { name: "Styrian Fox", id: "styrian-fox" },
  { name: "Styrian Golding", id: "styrian-golding" },
  { name: "Styrian Kolibri", id: "styrian-kolibri" },
  { name: "Styrian Wolf", id: "styrian-wolf" },
  { name: "African Queen", id: "african-queen" },
  { name: "Southern", id: "southern" },
  { name: "Southern Brewer", id: "southern-brewer" },
  { name: "Southern Dawn", id: "southern-dawn" },
  { name: "Southern Passion", id: "southern-passion" },
  { name: "Southern Promise", id: "southern-promise" },
  { name: "Southern Star", id: "southern-star" },
  { name: "Southern Sublime", id: "southern-sublime" },
  { name: "Southern Tropic", id: "southern-tropic" },
  { name: "XJA2/436", id: "xja2-436" },
  { name: "Zagrava", id: "zagrava" },
  { name: "Admiral", id: "admiral" },
  { name: "Archer", id: "archer" },
  { name: "Beata", id: "beata" },
  { name: "Boadicea", id: "boadicea" },
  { name: "Bramling Cross", id: "bramling-cross" },
  { name: "Challenger", id: "challenger" },
  { name: "Defender", id: "defender" },
  { name: "East Kent Goldings", id: "east-kent-goldings" },
  { name: "Endeavour", id: "endeavour" },
  { name: "Epic", id: "epic" },
  { name: "Ernest", id: "ernest" },
  { name: "First Gold", id: "first-gold" },
  { name: "Flyer", id: "flyer" },
  { name: "Fuggle", id: "fuggle" },
  { name: "Godiva", id: "godiva" },
  { name: "Hallertau Taurus", id: "hallertau-taurus" },
  { name: "Harlequin", id: "harlequin" },
  { name: "Herald", id: "herald" },
  { name: "Jester", id: "jester" },
  { name: "Minstrel", id: "minstrel" },
  { name: "Mystic", id: "mystic" },
  { name: "Olicana", id: "olicana" },
  { name: "Omega", id: "omega" },
  { name: "Phoenix", id: "phoenix" },
  { name: "Pilgrim", id: "pilgrim" },
  { name: "Pilot", id: "pilot" },
  { name: "Pioneer", id: "pioneer" },
  { name: "Progress", id: "progress" },
  { name: "Sovereign", id: "sovereign" },
  { name: "Sussex", id: "sussex" },
  { name: "Target", id: "target" },
  {
    name: "Whitbread Golding Variety (WGV)",
    id: "whitbread-golding-variety-wgv",
  },
  { name: "Yeoman", id: "yeoman" },
  { name: "Adeena", id: "adeena" },
  { name: "Ahhhroma", id: "ahhhroma" },
  { name: "Ahtanum", id: "ahtanum" },
  { name: "Aloha Blend", id: "aloha-blend" },
  { name: "Altus", id: "altus" },
  { name: "Amarillo", id: "amarillo" },
  { name: "Apollo", id: "apollo" },
  { name: "Aquila", id: "aquila" },
  { name: "Arcadian", id: "arcadian" },
  { name: "Azacca", id: "azacca" },
  { name: "Banner", id: "banner" },
  { name: "Belma", id: "belma" },
  { name: "Bergamot", id: "bergamot" },
  { name: "Bianca", id: "bianca" },
  { name: "Bitter Gold", id: "bitter-gold" },
  { name: "Bravo", id: "bravo" },
  { name: "Brewer's Gold (US)", id: "brewers-gold-us" },
  { name: "BRU-1", id: "bru-1" },
  { name: "Bullion", id: "bullion" },
  { name: "Buzz Bullets", id: "buzz-bullets" },
  { name: "Caliente", id: "caliente" },
  { name: "Calypso", id: "calypso" },
  { name: "Cascade", id: "cascade" },
  { name: "Cashmere", id: "cashmere" },
  { name: "Centennial", id: "centennial" },
  { name: "Chelan", id: "chelan" },
  { name: "Chinook", id: "chinook" },
  { name: "Citra", id: "citra" },
  { name: "Cluster", id: "cluster" },
  { name: "Cluster Fugget Blend", id: "cluster-fugget-blend" },
  { name: "Columbia", id: "columbia" },
  { name: "Columbus", id: "columbus" },
  { name: "Comet", id: "comet" },
  { name: "Contessa", id: "contessa" },
  { name: "Crystal", id: "crystal" },
  { name: "CTZ", id: "ctz" },
  { name: "Delta", id: "delta" },
  { name: "Diamond Springs", id: "diamond-springs" },
  { name: "Ekuanot", id: "ekuanot" },
  { name: "El Dorado", id: "el-dorado" },
  { name: "Emerald Spire", id: "emerald-spire" },
  { name: "Equinox", id: "equinox" },
  { name: "Eroica", id: "eroica" },
  { name: "Eureka", id: "eureka" },
  { name: "Evergreen Blend", id: "evergreen-blend" },
  { name: "Falconer's Flight", id: "falconers-flight" },
  { name: "Falconer's Flight 7CS", id: "falconers-flight-7cs" },
  { name: "Fantasia Blend", id: "fantasia-blend" },
  { name: "Galena", id: "galena" },
  { name: "Gemini", id: "gemini" },
  { name: "Glacier", id: "glacier" },
  { name: "Golding", id: "golding" },
  { name: "Grungeist", id: "grungeist" },
  { name: "Hallertau (US)", id: "hallertau-us" },
  { name: "Hartwick", id: "hartwick" },
  { name: "HBC 472", id: "hbc-472" },
  { name: "HBC 586", id: "hbc-586" },
  { name: "HBC 630", id: "hbc-630" },
  { name: "HBC 692", id: "hbc-692" },
  { name: "Helios", id: "helios" },
  { name: "Horizon", id: "horizon" },
  { name: "Hydra", id: "hydra" },
  { name: "Idaho 7", id: "idaho-7" },
  { name: "Idaho Gem", id: "idaho-gem" },
  { name: "Independence", id: "independence" },
  { name: "Jarrylo", id: "jarrylo" },
  { name: "Lambic", id: "lambic" },
  { name: "Lawton", id: "lawton" },
  { name: "Lemondrop", id: "lemondrop" },
  { name: "Liberty", id: "liberty" },
  { name: "Loral", id: "loral" },
  { name: "Lotus", id: "lotus" },
  { name: "Mackinac", id: "mackinac" },
  { name: "Magnum (US)", id: "magnum-us" },
  { name: "McKenzie", id: "mckenzie" },
  { name: "Medusa", id: "medusa" },
  { name: "Meridian", id: "meridian" },
  { name: "Michigan Copper", id: "michigan-copper" },
  { name: "Millennium", id: "millennium" },
  { name: "Mosaic", id: "mosaic" },
  { name: "Mount Hood", id: "mount-hood" },
  { name: "Mount Rainier", id: "mount-rainier" },
  { name: "Multihead", id: "multihead" },
  { name: "Newport", id: "newport" },
  { name: "Nobility Blend", id: "nobility-blend" },
  { name: "Northdown", id: "northdown" },
  { name: "Northern Brewer (US)", id: "northern-brewer-us" },
  { name: "Nugget", id: "nugget" },
  { name: "Old Mission", id: "old-mission" },
  { name: "Olympic", id: "olympic" },
  { name: "Pacific Crest", id: "pacific-crest" },
  { name: "Pahto", id: "pahto" },
  { name: "Palisade", id: "palisade" },
  { name: "Paradigm", id: "paradigm" },
  { name: "Pekko", id: "pekko" },
  { name: "Perle (US)", id: "perle-us" },
  { name: "Petoskey", id: "petoskey" },
  { name: "Prussian", id: "prussian" },
  { name: "Saaz (US)", id: "saaz-us" },
  { name: "Sabro", id: "sabro" },
  { name: "Samba", id: "samba" },
  { name: "Santiam", id: "santiam" },
  { name: "Satus", id: "satus" },
  { name: "Saugatuck", id: "saugatuck" },
  { name: "Sequoia Blend", id: "sequoia-blend" },
  { name: "Shaddock", id: "shaddock" },
  { name: "Simcoe", id: "simcoe" },
  { name: "Sitiva Blend", id: "sitiva-blend" },
  { name: "Sonnet", id: "sonnet" },
  { name: "Sterling", id: "sterling" },
  { name: "Sticky Fingers Blend", id: "sticky-fingers-blend" },
  { name: "Stirling", id: "stirling" },
  { name: "Strata", id: "strata" },
  { name: "Sultana (Denali)", id: "sultana-denali" },
  { name: "Summit", id: "summit" },
  { name: "Sun", id: "sun" },
  { name: "Sunbeam", id: "sunbeam" },
  { name: "Super Galena", id: "super-galena" },
  { name: "Tahoma", id: "tahoma" },
  { name: "Talisman", id: "talisman" },
  { name: "Talus", id: "talus" },
  { name: "Teamaker", id: "teamaker" },
  { name: "Tettnang (US)", id: "tettnang-us" },
  { name: "Tillicum", id: "tillicum" },
  { name: "TNT Blend", id: "tnt-blend" },
  { name: "Tomahawk", id: "tomahawk" },
  { name: "Trident", id: "trident" },
  { name: "TriplePearl", id: "triplepearl" },
  { name: "Triumph", id: "triumph" },
  { name: "Tropica", id: "tropica" },
  { name: "Ultra", id: "ultra" },
  { name: "USDA 008", id: "usda-008" },
  { name: "Vanguard", id: "vanguard" },
  { name: "Vista", id: "vista" },
  { name: "Walhalla", id: "walhalla" },
  { name: "Warrior", id: "warrior" },
  { name: "Wild Wolf", id: "wild-wolf" },
  { name: "Willamette", id: "willamette" },
  { name: "X13459", id: "x13459" },
  { name: "Yakima Cluster", id: "yakima-cluster" },
  { name: "Yakima Gold", id: "yakima-gold" },
  { name: "YQH-1380", id: "yqh-1380" },
  { name: "Zamba Blend", id: "zamba-blend" },
  { name: "Zappa", id: "zappa" },
  { name: "Zenia", id: "zenia" },
  { name: "Zenith", id: "zenith" },
  { name: "Zeus", id: "zeus" },
];

// Suggested malts in CategorySelect and Autocomplete
const maltSuggestions = [
  { id: "pale-malt", name: "Pale Malt" },
  { id: "pilsner", name: "Pilsner" },
  { id: "maris-otter", name: "Maris Otter" },
  { id: "vienna", name: "Vienna" },
  { id: "munich", name: "Munich" },
  { id: "wheat", name: "Wheat" },
  {
    id: "crystal/caramel",
    name: "Crystal/Caramel",
  },
  { id: "rye", name: "Rye" },
  { id: "aromatic", name: "Aromatic" },
  { id: "biscuit", name: "Biscuit" },
  { id: "special-b", name: "Special B" },
  { id: "roasted-barley", name: "Roasted Barley" },
  { id: "chocolate -alt", name: "Chocolate Malt" },
  { id: "black-patent", name: "Black Patent" },
  { id: "carapils/dextrin", name: "Carapils/Dextrin" },
  { id: "flaked-oats", name: "Flaked Oats" },
  { id: "flaked-barley", name: "Flaked Barley" },
  { id: "flaked-wheat", name: "Flaked Wheat" },
  { id: "carafoam", name: "Carafoam" },
  { id: "caramunich", name: "CaraMunich" },
  { id: "carafa-special-I", name: "Carafa Special I" },
  { id: "carafa-special-II", name: "Carafa Special II" },
  { id: "carafa-special-III", name: "Carafa Special III" },
  { id: "honey-malt", name: "Honey Malt" },
  { id: "victory", name: "Victory" },
  { id: "acidulated", name: "Acidulated" },
  { id: "smoked-malt", name: "Smoked Malt" },
  { id: "melanoidin", name: "Melanoidin" },
  { id: "amber", name: "Amber" },
  { id: "pale-wheat", name: "Pale Wheat" },
  { id: "dark-munich", name: "Dark Munich" },
  { id: "aromatic-munich", name: "Aromatic Munich" },
  { id: "carared", name: "Carared" },
  { id: "roasted-wheat", name: "Roasted Wheat" },
  { id: "peated-malt", name: "Peated Malt" },
  { id: "caramel-wheat", name: "Caramel Wheat" },
  { id: "caramel-rye", name: "Caramel Rye" },
  { id: "caraaroma", name: "CaraAroma" },
  { id: "carabrown", name: "Carabrown" },
  { id: "spelt", name: "Spelt" },
  { id: "raw-wheat", name: "Raw Wheat" },
  { id: "raw-rye", name: "Raw Rye" },
  { id: "oat", name: "Oat" },
  { id: "coffee-malt", name: "Coffee Malt" },
  { id: "midnight-wheat", name: "Midnight Wheat" },
  { id: "roasted-buckwheat", name: "Roasted Buckwheat" },
  { id: "kiln-coffee-malt", name: "Kiln Coffee Malt" },
  { id: "belgian-special-b", name: "Belgian Special B" },
  { id: "belgian-aromatic", name: "Belgian Aromatic" },
  { id: "belgian-biscuit", name: "Belgian Biscuit" },
];

export { hopSuggestions, maltSuggestions };
