// Suggested hops in CategorySelect and Autocomplete
const hopSuggestions = [
  { id: "cascade", name: "Cascade" },
  { id: "centennial", name: "Centennial" },
  { id: "citra", name: "Citra" },
  { id: "columbus", name: "Columbus" },
  { id: "amarillo", name: "Amarillo" },
  { id: "simcoe", name: "Simcoe" },
  { id: "chinook", name: "Chinook" },
  { id: "hallertau-mittelfruh", name: "Hallertau Mittelfrüh" },
  { id: "saaz", name: "Saaz" },
  { id: "tettnang", name: "Tettnang" },
  { id: "fuggle", name: "Fuggle" },
  { id: "willamette", name: "Willamette" },
  { id: "east-kent-goldings", name: "East Kent Goldings" },
  { id: "galaxy", name: "Galaxy" },
  { id: "mosaic", name: "Mosaic" },
  { id: "nelson-sauvin", name: "Nelson Sauvin" },
  { id: "sorachi-ace", name: "Sorachi Ace" },
  { id: "styrian-goldings", name: "Styrian Goldings" },
  { id: "magnum", name: "Magnum" },
  { id: "perle", name: "Perle" },
];

// Suggested malts in CategorySelect and Autocomplete
const maltSuggestions = [
  { id: "pale-malt", name: "Pale Malt" },
  { id: "pilsner", name: "Pilsner" },
  { id: "maris-otter", name: "Maris Otter" },
  { id: "vienna", name: "Vienna" },
  { id: "munich", name: "Munich" },
  { id: "wheat", name: "Wheat" },
  {
    id: "crystal/caramel-(various-levels-of-darkness)",
    name: "Crystal/Caramel (various levels of darkness)",
  },
  { id: "rye", name: "Rye" },
  { id: "aromatic", name: "Aromatic" },
  { id: "biscuit", name: "Biscuit" },
  { id: "special-b", name: "Special B" },
  { id: "roasted-barley", name: "Roasted Barley" },
  { id: "chocolate -alt", name: "Chocolate Malt" },
  { id: "black-patent", name: "Black Patent" },
  { id: "carapils/dextrin", name: "Carapils/Dextrin" },
  { id: "flaked-oats", name: "Flaked Oats" },
  { id: "flaked-barley", name: "Flaked Barley" },
  { id: "flaked-wheat", name: "Flaked Wheat" },
  { id: "carafoam", name: "Carafoam" },
  { id: "caramunich", name: "CaraMunich" },
  { id: "carafa-special-I", name: "Carafa Special I" },
  { id: "carafa-special-II", name: "Carafa Special II" },
  { id: "carafa-special-III", name: "Carafa Special III" },
  { id: "honey-malt", name: "Honey Malt" },
  { id: "victory", name: "Victory" },
  { id: "acidulated", name: "Acidulated" },
  { id: "smoked-malt", name: "Smoked Malt" },
  { id: "melanoidin", name: "Melanoidin" },
  { id: "amber", name: "Amber" },
  { id: "pale-wheat", name: "Pale Wheat" },
  { id: "dark-munich", name: "Dark Munich" },
  { id: "aromatic-munich", name: "Aromatic Munich" },
  { id: "carared", name: "Carared" },
  { id: "roasted-wheat", name: "Roasted Wheat" },
  { id: "peated-malt", name: "Peated Malt" },
  { id: "caramel-wheat", name: "Caramel Wheat" },
  { id: "caramel-rye", name: "Caramel Rye" },
  { id: "caraaroma", name: "CaraAroma" },
  { id: "carabrown", name: "Carabrown" },
  { id: "spelt", name: "Spelt" },
  { id: "raw-wheat", name: "Raw Wheat" },
  { id: "raw-rye", name: "Raw Rye" },
  { id: "oat", name: "Oat" },
  { id: "coffee-malt", name: "Coffee Malt" },
  { id: "midnight-wheat", name: "Midnight Wheat" },
  { id: "roasted-buckwheat", name: "Roasted Buckwheat" },
  { id: "kiln-coffee-malt", name: "Kiln Coffee Malt" },
  { id: "belgian-special-b", name: "Belgian Special B" },
  { id: "belgian-aromatic", name: "Belgian Aromatic" },
  { id: "belgian-biscuit", name: "Belgian Biscuit" },
];

export { hopSuggestions, maltSuggestions };
