import "./globals.css";
import { Inter } from "next/font/google";
import Chat from "@/components/Chat";
import Provider from "@/components/Provider";
import { useSession } from "next-auth/react";
import { Metadata } from "next";
import NavBar from "@/components/NavBar";
import { getServerSession } from "next-auth";
import { authOptions } from "./api/auth/[...nextauth]/route";
import getUser from "@/lib/getUser";
import getBreweries from "@/lib/getBreweries";
import { Session } from "inspector";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Beer Flow",
  description: "Generated by create next app",
};
// Segment-level Caching. Revalidate data every 60 seconds app wide
export const revalidate = 86400; // 1 day

export default async function Layout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession(authOptions);

  const user = await getUser(session);
  const breweries = await getBreweries(user, session);
  return (
    <html lang="en">
      <Provider>
        <body className={inter.className}>
          <NavBar breweries={breweries} />
          {/* <Chat /> */}
          {children}
        </body>
      </Provider>
    </html>
  );
}
