import NavBar from "@/components/NavBar";
import Provider from "@/components/Provider";
import getBreweries from "@/lib/getBreweries";
import { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { User, getServerSession } from "next-auth";
import { authOptions } from "./api/auth/[...nextauth]/route";
import Dashboard from "@/components/Dashboard/Dashboard";
import { Brewery } from "./types/brewery";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Beer Flow",
  description: "Generated by create next app",
};
// Segment-level Caching. Revalidate data every 60 seconds app wide
export const revalidate = 86400; // 1 day

export default async function Layout(props: {
  children: React.ReactNode;
  modal: React.ReactNode;
}) {
  const breweries = await getBreweries();
  const session = await getServerSession(authOptions);

  const adminAllowed = breweries.map((brewery: Brewery) =>
    brewery.admin.includes(session?.user._id)
  );
  return (
    <html lang="en">
      <Provider>
        <body className={inter.className}>
          {/* @ts-expect-error Server Component */}
          {session && <NavBar breweries={breweries} user={session} />}
          {adminAllowed && <Dashboard breweries={breweries} />}
          {/* <Chat /> */}
          {props.children}
          {props.modal}
        </body>
      </Provider>
    </html>
  );
}
